spring:
  application:
    name: dossier-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        hostname: dossier-service
        health-check-path: /actuator/health
      host: consul-server
      port: 8500

server:
  port: 8083

---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-ms:5432/dossier-db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect