services:
  postgres:
    container_name: postgres-ms
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - consul-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username" ]
      interval: 10s
      timeout: 5s
      retries: 5

  consul:
    image: consul:1.15.0
    container_name: consul-server
    command: "agent -server -ui -node=consul-server -bootstrap-expect=1 -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - consul-data:/consul/data
    networks:
      - consul-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8500/v1/status/leader || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

#  config-service:
#    build: ./config-service
#    container_name: config-service
#    ports:
#      - "8888:8888"
#    networks:
#      - consul-network
#    environment:
#      - SPRING_CLOUD_CONSUL_HOST=consul
#      - SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME=config-service
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5

  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "8081:8081"
    networks:
      - consul-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME: patient-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - consul
      - postgres

  rdv-service:
    build: ./rdv-service
    container_name: rdv-service
    ports:
      - "8082:8082"
    networks:
      - consul-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME: rdv-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - consul
      - postgres

  dossier-service:
    build: ./dossier-service
    container_name: dossier-service
    ports:
      - "8083:8083"
    networks:
      - consul-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME: dossier-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - consul
      - postgres

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "9999:9999"
    networks:
      - consul-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME: gateway
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - consul


volumes:
  consul-data:
  postgres_data:

networks:
  consul-network:
    driver: bridge