spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        hostname: gateway-service
      host: consul-server
      port: 8500
