server:
  http_listen_port: 3200

distributor:
  receivers:
    zipkin:
      endpoint: 0.0.0.0:9411  # Écoute les spans Zipkin

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks