spring:
  application:
    name: patient-service
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        hostname: patient-service
        health-check-path: /actuator/health
      host: consul-server
      port: 8500

server:
  port: 8081

---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-ms:5432/patient-db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
