spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true

server:
  port: 8888


